### ISSUE TITLE
i can't load Ajax on my form even there is no errors inside the code

### ISSUE THREAD

**Issue by SamadShakir** [SamadShakir/Issue#1]
i have issue with ajax , if i change the condition ( if resp="false" ) for exemple it adds the HTML line to the code , i dont know where is the problem exactly 
The Code in JS file :

> $(document).ready(function(){
>       //check admin password
>       $("#cpwd").keyup(function(){
>           var cpwd = $("#cpwd").val();
>           $.ajax({
>               type:'post',
>               url:'/admin/cpwd',
>               data:{cpwd:cpwd},
>               success:function(resp){
>                   if(resp=="false"){
>                       $("#chkPwd").html("<font color=red>Your Current Password is incorrect</font>");
>                   }else if(resp=="true"){
>                       $("#chkPwd").html("<font color=green>Your Current Password is correct</font>");
>                   }
>               },error:function(){
>                   alert("error");
>               }
> 
>           });
> 
>       });
> });

HTML 

> @extends('layouts.admin_layout.admin_layout')
>   @section('content')
>   
>   <div class="content-wrapper">
>     
>     <div class="content-header">
>       <div class="container-fluid">
>         <div class="row mb-2">
>           <div class="col-sm-6">
>             <h1 class="m-0 text-dark">Settings</h1>
>           </div>
>           <div class="col-sm-6">
>             <ol class="breadcrumb float-sm-right">
>               <li class="breadcrumb-item"><a href="#">Home</a></li>
>               <li class="breadcrumb-item active">ASettings</li>
>             </ol>
>           </div>
>         </div>
>       </div>
>     </div>
>     
> 
>     
>     <section class="content">
>       <div class="container-fluid">
>         <div class="row">
>           
>           <div class="col-md-6">
>             
>             <div class="card card-primary">
>               <div class="card-header">
>                 <h3 class="card-title">MAJ Password</h3>
>               </div>
>               
>               
>               <form role="form" method="post" action="{{url('/admin/update-pwd')}}" name="updatePasswordForm" id="updatePasswordForm">
>                 <div class="card-body">
>                   <div class="form-group">
>                     <label for="exampleInputEmail1">Email address</label>
>                     <input type="email" class="form-control" value="{{Auth::guard('admin')->user()->email}}" readonly="">
>                   </div>
>                   <div class="form-group">
>                     <label for="exampleInputEmail1">Admin TYPE</label>
>                     <input type="email" class="form-control" value="{{Auth::guard('admin')->user()->type}}" readonly="">
>                   </div>
>                   <div class="form-group">
>                     <label>Current Password</label>
>                     <input type="password" class="form-control" name="cpwd" id="cpwd" placeholder="Enter Your Current Password">
>                     <span id="chkPwd"></span>
>                     <span toggle="#cpwd" class="fa fa-fw fa-eye field-icon toggle-password"></span>
>                   </div>
>                   <div class="form-group">
>                     <label>New Password</label>
>                     <input type="password" class="form-control" name="n_pwd" id="n_pwd" placeholder="Enter Your New Password">
>                     <span toggle="#n_pwd" class="fa fa-fw fa-eye field-icon toggle-password"></span>
>                   </div>
>                   <div class="form-group">
>                     <label>Confirm New Password</label>
>                     <input type="password" class="form-control" name="con_pwd" id="con_pwd" placeholder="Repeat Your New Password">
>                     <span toggle="#con_pwd" class="fa fa-fw fa-eye field-icon toggle-password"></span>
>                   </div>
> 
>                 </div>
>                 
> 
>                 <div class="card-footer">
>                   <button type="submit" class="btn btn-primary">Submit</button>
>                 </div>
>               </form>
>             </div>
>             
>           </div>
>           
>         </div>
>         
>       </div>
>     </section>
>     
>   </div>
>   
>   @endsection

**Comment by SamadShakir** [comment]
i got this error in console 
jquery.min.js:2 Uncaught TypeError: Cannot set property 'innerHTML' of undefined
    at new Sparkline (sparkline.js:28)
    at HTMLDocument.<anonymous> (dashboard.js:92)
    at e (jquery.min.js:2)
    at t (jquery.min.js:2)
and this warning 
jquery.min.js:2 jQuery.Deferred exception: Cannot set property 'innerHTML' of undefined TypeError: Cannot set property 'innerHTML' of undefined
    at new Sparkline (http://127.0.0.1:8000/plugins/sparklines/sparkline.js:28:30)
    at HTMLDocument.<anonymous> (http://127.0.0.1:8000/js/backend/pages/dashboard.js:92:20)
    at e (http://127.0.0.1:8000/plugins/jquery/jquery.min.js:2:29453)
    at t (http://127.0.0.1:8000/plugins/jquery/jquery.min.js:2:29755) undefined
